# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empDataLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(998, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setMaximumSize(QtCore.QSize(1000, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/png/UVUMonogramGreen-0005.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-image: url(:/icons/assets/png/UVUMonogramGreen-0005.png);\n"
"background-width: 600px;\n"
"background-repeat: no-repeat; \n"
"background-position: center;\n"
"background-color: black; \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(150, 150, 150, 150)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_frame = QtWidgets.QFrame(self.centralwidget)
        self.login_frame.setStyleSheet("background-color: rgb(255,255,255,180);\n"
"border-width: 2px;\n"
"border-color: green;\n"
"border-radius: 20px;\n"
"")
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.login_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.login_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 85))
        self.frame_2.setStyleSheet("background-color: transparent;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.employeeIdLogin_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.employeeIdLogin_label.sizePolicy().hasHeightForWidth())
        self.employeeIdLogin_label.setSizePolicy(sizePolicy)
        self.employeeIdLogin_label.setMinimumSize(QtCore.QSize(180, 20))
        self.employeeIdLogin_label.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.employeeIdLogin_label.setFont(font)
        self.employeeIdLogin_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.employeeIdLogin_label.setObjectName("employeeIdLogin_label")
        self.horizontalLayout_2.addWidget(self.employeeIdLogin_label)
        self.employeeIdLogin_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.employeeIdLogin_lineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.employeeIdLogin_lineEdit.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.employeeIdLogin_lineEdit.setFont(font)
        self.employeeIdLogin_lineEdit.setStyleSheet("border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 10px;\n"
"background-color: white;")
        self.employeeIdLogin_lineEdit.setText("")
        self.employeeIdLogin_lineEdit.setObjectName("employeeIdLogin_lineEdit")
        self.horizontalLayout_2.addWidget(self.employeeIdLogin_lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.login_frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 85))
        self.frame_3.setStyleSheet("background-color: transparent;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.passwordLogin_label = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordLogin_label.sizePolicy().hasHeightForWidth())
        self.passwordLogin_label.setSizePolicy(sizePolicy)
        self.passwordLogin_label.setMinimumSize(QtCore.QSize(180, 20))
        self.passwordLogin_label.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLogin_label.setFont(font)
        self.passwordLogin_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLogin_label.setObjectName("passwordLogin_label")
        self.horizontalLayout_3.addWidget(self.passwordLogin_label)
        self.passwordLogin_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.passwordLogin_lineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.passwordLogin_lineEdit.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.passwordLogin_lineEdit.setFont(font)
        self.passwordLogin_lineEdit.setStyleSheet("border-radius: 15px;\n"
"padding: 5px;\n"
"padding-left: 10px;\n"
"background-color: white;")
        self.passwordLogin_lineEdit.setText("")
        self.passwordLogin_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLogin_lineEdit.setObjectName("passwordLogin_lineEdit")
        self.horizontalLayout_3.addWidget(self.passwordLogin_lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.login_frame)
        self.frame_5.setStyleSheet("background-color: transparent;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.login_toolButton = QtWidgets.QToolButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_toolButton.setFont(font)
        self.login_toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_toolButton.setStyleSheet("QToolButton {\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"background-color: rgb(120, 190, 72);\n"
"color: white;\n"
"padding: 4px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"padding-top: 6px;\n"
"background-color: rgb(120, 190, 72);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"padding-top: 8px;\n"
"background-color: rgb(90, 160, 42);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: rgba(0, 0, 0, 70);\n"
"background-color: rgba(120, 190, 72, 70);\n"
"color: rgba(255, 255, 255, 70);\n"
"padding: 4px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}")
        self.login_toolButton.setObjectName("login_toolButton")
        self.horizontalLayout_4.addWidget(self.login_toolButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout.addWidget(self.login_frame)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Employee Data Login"))
        self.employeeIdLogin_label.setText(_translate("LoginWindow", "Employee ID: "))
        self.passwordLogin_label.setText(_translate("LoginWindow", "  Password: "))
        self.login_toolButton.setText(_translate("LoginWindow", "Login"))
import Resources_rc
